services:
  - type: web
    name: vitalityboost-frontend
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
